"""The skill pack (AI-08): short guides in the open Agent Skills format that
teach any AI assistant the right way to build, wire, check and explain
LightSim models.

The guides live in ``skills/<name>/SKILL.md``. Two reference files are
generated, so they never drift from the app:

- ``lightsim-units-and-parameters/references/components.md`` from the
  component library (``app/library/components.json``),
- ``lightsim-what-it-cannot-do/references/known-limits.md`` from
  ``docs/KNOWN-LIMITS.md``.

Regenerate them with ``python -m app.ai.skillpack --write`` (run from
``backend/``); a test fails when they are out of date. The MCP server serves
every file of the pack as a resource (``lightsim://skills/...``).
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Optional

from ..library import load_library, unit_groups
from ..paths import BUNDLE_DIR

SKILLS_DIR = Path(__file__).parent / "skills"
#: The pack's version: bump it when a guide changes meaning.
PACK_VERSION = "0.3.0"
COMPONENTS_REF = SKILLS_DIR / "lightsim-units-and-parameters" / "references" / "components.md"
LIMITS_REF = SKILLS_DIR / "lightsim-what-it-cannot-do" / "references" / "known-limits.md"
_GENERATED = "<!-- Generated by `python -m app.ai.skillpack --write` from {src}. Do not edit. -->"


def skill_files() -> list[Path]:
    """Every file of the pack, sorted (SKILL.md files and references)."""
    if not SKILLS_DIR.is_dir():
        return []
    return sorted(p for p in SKILLS_DIR.rglob("*") if p.is_file() and p.suffix in (".md", ".txt"))


def skills() -> list[dict]:
    """Name and description of each skill, from its SKILL.md front matter."""
    out = []
    for f in sorted(SKILLS_DIR.glob("*/SKILL.md")):
        meta = front_matter(f.read_text(encoding="utf-8"))
        out.append({"name": meta.get("name", f.parent.name),
                    "description": meta.get("description", ""), "path": f})
    return out


def front_matter(text: str) -> dict[str, str]:
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        return {}
    out = {}
    for line in m.group(1).splitlines():
        if ":" in line and not line.startswith((" ", "\t")):
            key, value = line.split(":", 1)
            out[key.strip()] = value.strip().strip('"')
    return out


def _fmt_default(value: object, unit: str) -> str:
    if isinstance(value, bool):
        return "on" if value else "off"
    if isinstance(value, (int, float)):
        u = "" if unit == "-" else f" {unit}"
        return f"{value:g}{u}"
    if isinstance(value, dict):
        return "table"
    text = str(value)
    return "code" if "\n" in text else f"`{text}`"


def components_markdown() -> str:
    """The library as a reference: each part's ports and parameters."""
    groups = unit_groups()
    lines = [_GENERATED.format(src="backend/app/library/components.json"), "",
             "# LightSim component reference", "",
             "Every part in LightSim's library: its id (the `type` for model_edit's `add`), its "
             "ports (`id`: name, kind, direction) and its parameters (`key`: label, unit, "
             "default, limits). Values are given in the unit listed; there is no unit conversion.",
             ""]
    for c in load_library():
        if c.id == "container.system":
            continue
        lines += [f"## {c.name} (`{c.id}`)", "", f"Category: {c.category}. Domain: {c.domain}.", ""]
        if c.description:
            lines += [c.description, ""]
        if c.ports:
            lines.append("Ports:")
            for p in c.ports:
                unit = f", {groups.get(p.unitGroup, p.unitGroup)}" if p.unitGroup else ""
                lines.append(f"- `{p.id}`: {p.name} ({p.kind} {p.direction}{unit})")
            lines.append("")
        elif c.allowDynamicPorts:
            lines += ["Ports: none until you add signal ports to the part.", ""]
        if c.parameters:
            lines.append("Parameters:")
            for p in c.parameters:
                limits = []
                if p.exclusiveMinimum is not None:
                    limits.append(f"> {p.exclusiveMinimum:g}")
                elif p.minimum is not None:
                    limits.append(f"≥ {p.minimum:g}")
                if p.maximum is not None:
                    limits.append(f"≤ {p.maximum:g}")
                extra = f"; {' and '.join(limits)}" if limits else ""
                if p.options:
                    extra += f"; one of {', '.join(p.options)}"
                unit = "" if p.unit == "-" else f" [{p.unit}]"
                lines.append(f"- `{p.key}`: {p.label}{unit}, default "
                             f"{_fmt_default(p.default, p.unit)}{extra}")
            lines.append("")
        if c.presets:
            lines.append("Presets: " + ", ".join(p.name for p in c.presets))
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _limits_source() -> Optional[Path]:
    for candidate in (BUNDLE_DIR.parent / "docs" / "KNOWN-LIMITS.md", BUNDLE_DIR / "KNOWN-LIMITS.md"):
        if candidate.is_file():
            return candidate
    return None


def _first_sentence(text: str, limit: int = 260) -> str:
    text = " ".join(text.split())
    text = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", text)  # drop link targets
    m = re.match(r"(.+?[.!?])(\s|$)", text)
    s = m.group(1) if m else text
    return s if len(s) <= limit else s[: limit - 1] + "…"


def known_limits_markdown(source: Optional[Path] = None) -> str:
    """The Known Limits page cut to its headings, each item's bold lead and
    the first sentence after it."""
    source = source or _limits_source()
    if source is None:
        raise FileNotFoundError("docs/KNOWN-LIMITS.md")
    text = source.read_text(encoding="utf-8")
    lines = [_GENERATED.format(src="docs/KNOWN-LIMITS.md"), "",
             "# What LightSim cannot do (summary of Known Limits)", "",
             "Read the full page before relying on a number: "
             "https://github.com/Eyad-3D/simstudio/blob/main/docs/KNOWN-LIMITS.md", ""]
    blocks = re.split(r"\n(?=#{2,3} )", text)
    for block in blocks[1:]:
        heading, _, body = block.partition("\n")
        level = heading.count("#", 0, 3)
        lines += [("## " if level == 2 else "### ") + heading.lstrip("# ").strip(), ""]
        items = re.findall(r"^- \*\*(.+?)\*\*(.*?)(?=^- |\Z)", body, re.S | re.M)
        if items:
            for lead, rest in items:
                tail = _first_sentence(rest.strip())
                lines.append(f"- **{lead.strip()}** {tail}".rstrip())
            lines.append("")
        else:
            paragraph = body.strip().split("\n\n")[0] if body.strip() else ""
            if paragraph and not paragraph.startswith("#"):
                lines += [_first_sentence(paragraph, 400), ""]
    return "\n".join(lines).rstrip() + "\n"


def known_limit_sections(text: str, limit: int = 3) -> list[str]:
    """The known limits whose words best match ``text``, as one line each."""
    try:
        ref = LIMITS_REF.read_text(encoding="utf-8")
    except OSError:
        return []
    words = {w for w in re.findall(r"[a-z]{4,}", text.lower())}
    scored = []
    for line in ref.splitlines():
        if not line.startswith(("- ", "###")):
            continue
        hits = len(words & set(re.findall(r"[a-z]{4,}", line.lower())))
        if hits >= 2:
            scored.append((hits, line.lstrip("-# ").strip()))
    return [s for _, s in sorted(scored, key=lambda x: -x[0])[:limit]]


def generated() -> dict[Path, str]:
    return {COMPONENTS_REF: components_markdown(), LIMITS_REF: known_limits_markdown()}


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m app.ai.skillpack")
    parser.add_argument("--write", action="store_true", help="rewrite the generated references")
    args = parser.parse_args(argv)
    stale = []
    for path, text in generated().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != text:
            stale.append(path)
            if args.write:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8")
    for p in stale:
        print(("rewrote " if args.write else "out of date: ") + str(p.relative_to(SKILLS_DIR)))
    return 1 if stale and not args.write else 0


if __name__ == "__main__":
    sys.exit(main())
