/* -----------------------------------------------------------------
 * SUNDIALS configuration header for LightSim's in-tree build
 * (crates/lsim-sundials-sys). Written by hand once instead of being
 * generated by CMake from sundials_config.in, so the build needs only a
 * C compiler. One header serves every platform: the few compiler-specific
 * settings are chosen by the preprocessor below.
 *
 * Build: SUNDIALS 7.1.1, double precision, 64-bit indices, serial only
 * (no MPI, no threads, no GPU, no third-party libraries), no logging, no
 * profiling, error checks off (the settings of a CMake Release build).
 *
 * SUNDIALS is Copyright (c) 2002-2024, Lawrence Livermore National
 * Security and Southern Methodist University; BSD-3-Clause, see the
 * LICENSE and NOTICE files next to these sources.
 * SPDX-License-Identifier: BSD-3-Clause
 * -----------------------------------------------------------------*/

#ifndef _SUNDIALS_CONFIG_H
#define _SUNDIALS_CONFIG_H

#include "sundials/sundials_export.h"

#if defined(__cplusplus)
#define SUNDIALS_NOEXCEPT noexcept
#else
#define SUNDIALS_NOEXCEPT
#endif

#ifndef SUNDIALS_DEPRECATED_MSG
#if defined(_MSC_VER) && !defined(__clang__)
#define SUNDIALS_DEPRECATED_MSG(msg) __declspec(deprecated(msg))
#else
#define SUNDIALS_DEPRECATED_MSG(msg) __attribute__((__deprecated__(msg)))
#endif
#endif

#ifndef SUNDIALS_DEPRECATED_EXPORT_MSG
#define SUNDIALS_DEPRECATED_EXPORT_MSG(msg) \
  SUNDIALS_EXPORT SUNDIALS_DEPRECATED_MSG(msg)
#endif

#ifndef SUNDIALS_DEPRECATED_NO_EXPORT_MSG
#define SUNDIALS_DEPRECATED_NO_EXPORT_MSG(msg) \
  SUNDIALS_NO_EXPORT SUNDIALS_DEPRECATED_MSG(msg)
#endif

/* version */
#define SUNDIALS_VERSION       "7.1.1"
#define SUNDIALS_VERSION_MAJOR 7
#define SUNDIALS_VERSION_MINOR 1
#define SUNDIALS_VERSION_PATCH 1
#define SUNDIALS_VERSION_LABEL ""
#define SUNDIALS_GIT_VERSION   ""

/* compiler features (hints only; GCC and Clang have them, MSVC does not) */
#if defined(__GNUC__) || defined(__clang__)
#define SUNDIALS_C_COMPILER_HAS_BUILTIN_EXPECT
#define SUNDIALS_C_COMPILER_HAS_ATTRIBUTE_UNUSED
#endif

/* sunrealtype is double; sunindextype is a 64-bit integer */
#define SUNDIALS_DOUBLE_PRECISION 1
#define SUNDIALS_INT64_T          1
#define SUNDIALS_INDEX_TYPE       int64_t

/* POSIX timers exist everywhere but Windows (used only when profiling) */
#if !defined(_WIN32)
#define SUNDIALS_HAVE_POSIX_TIMERS
#endif

/* no logging (errors reach the handler LightSim installs on each context) */
#define SUNDIALS_LOGGING_LEVEL 0

/* build metadata */
#define SUN_C_COMPILER         "cc (lsim-sundials-sys)"
#define SUN_C_COMPILER_VERSION ""
#define SUN_C_COMPILER_FLAGS   ""
#define SUN_CXX_COMPILER         ""
#define SUN_CXX_COMPILER_VERSION ""
#define SUN_CXX_COMPILER_FLAGS   ""
#define SUN_FORTRAN_COMPILER         ""
#define SUN_FORTRAN_COMPILER_VERSION ""
#define SUN_FORTRAN_COMPILER_FLAGS   ""
#define SUN_BUILD_TYPE         "Release"
#define SUN_JOB_ID             ""
#define SUN_JOB_START_TIME     ""
#define SUN_TPL_LIST           ""
#define SUN_TPL_LIST_SIZE      ""
#define SUNDIALS_SPACK_VERSION ""

/* third-party libraries: none */
#define SUN_GINKGO_VERSION         ""
#define SUN_HYPRE_VERSION          ""
#define SUN_KLU_VERSION            ""
#define SUN_KOKKOS_VERSION         ""
#define SUN_KOKKOS_KERNELS_VERSION ""
#define SUN_LAPACK_VERSION         ""
#define SUN_MAGMA_VERSION          ""
#define SUN_MPI_C_COMPILER         ""
#define SUN_MPI_C_VERSION          ""
#define SUN_MPI_CXX_COMPILER       ""
#define SUN_MPI_CXX_VERSION        ""
#define SUN_MPI_FORTRAN_COMPILER   ""
#define SUN_MPI_FORTRAN_VERSION    ""
#define SUN_ONEMKL_VERSION         ""
#define SUN_OPENMP_VERSION         ""
#define SUN_PETSC_VERSION          ""
#define SUN_PTHREADS_VERSION       ""
#define SUN_RAJA_VERSION           ""
#define SUN_SUPERLUDIST_VERSION    ""
#define SUN_SUPERLUMT_VERSION      ""
#define SUN_TRILLINOS_VERSION      ""
#define SUN_XBRAID_VERSION         ""
#define SUNDIALS_MPI_ENABLED 0
#define SUNDIALS_SUPERLUMT_THREAD_TYPE ""
#define SUN_CUDA_VERSION       ""
#define SUN_CUDA_COMPILER      ""
#define SUN_CUDA_ARCHITECTURES ""
#define SUN_HIP_VERSION        ""
#define SUN_AMDGPU_TARGETS     ""

/* the modules built */
#define SUNDIALS_CVODES 1
#define SUNDIALS_IDAS 1
#define SUNDIALS_KINSOL 1
#define SUNDIALS_NVECTOR_SERIAL 1
#define SUNDIALS_SUNMATRIX_BAND 1
#define SUNDIALS_SUNMATRIX_DENSE 1
#define SUNDIALS_SUNMATRIX_SPARSE 1
#define SUNDIALS_SUNLINSOL_BAND 1
#define SUNDIALS_SUNLINSOL_DENSE 1
#define SUNDIALS_SUNNONLINSOL_NEWTON 1
#define SUNDIALS_SUNNONLINSOL_FIXEDPOINT 1

#endif /* _SUNDIALS_CONFIG_H */
