// Central icon registry — maps the `icon` keys used in the component
// library JSON to lucide-react components, with a safe fallback.
import {
  Activity,
  Anchor,
  Asterisk,
  BatteryCharging,
  Box,
  Car,
  Circle,
  CircleDot,
  CloudSun,
  Code,
  Cog,
  Cylinder,
  Disc,
  Equal,
  Fan,
  Flag,
  Flame,
  Fuel,
  Gauge,
  GitBranch,
  GitFork,
  Layers,
  LoaderPinwheel,
  Minus,
  Mountain,
  Package,
  Plug,
  Route,
  Settings2,
  SlidersHorizontal,
  Table,
  Target,
  User,
  Zap,
  type LucideIcon,
} from "lucide-react";

const REGISTRY: Record<string, LucideIcon> = {
  zap: Zap,
  "circle-dot": CircleDot,
  plug: Plug,
  "battery-charging": BatteryCharging,
  fan: Fan,
  "sliders-horizontal": SlidersHorizontal,
  "loader-pinwheel": LoaderPinwheel,
  circle: Circle,
  minus: Minus,
  equal: Equal,
  route: Route,
  anchor: Anchor,
  "cloud-sun": CloudSun,
  box: Box,
  car: Car,
  cog: Cog,
  "git-fork": GitFork,
  disc: Disc,
  gauge: Gauge,
  code: Code,
  package: Package,
  asterisk: Asterisk,
  flame: Flame,
  fuel: Fuel,
  cylinder: Cylinder,
  layers: Layers,
  target: Target,
  "git-branch": GitBranch,
  "settings-2": Settings2,
  activity: Activity,
  table: Table,
  mountain: Mountain,
  user: User,
  flag: Flag,
};

export function componentIcon(key: string): LucideIcon {
  return REGISTRY[key] ?? Box;
}
