//! # lsim-sundials-sys: SUNDIALS, built in-tree
//!
//! Raw bindings to SUNDIALS 7.1.1 (BSD-3-Clause, Lawrence Livermore
//! National Security and Southern Methodist University; `sundials/LICENSE`
//! and `sundials/NOTICE`): CVODES and IDAS (CVODE and IDA with quadratures
//! and sensitivities), KINSOL, the serial vector, dense, band and sparse
//! (CSC) matrices, dense and band LU, and the Newton and fixed-point
//! nonlinear solvers. KLU (LGPL) is not included; lsim-solve supplies a
//! sparse LU of its own (faer, MIT) as a `SUNLinearSolver`.
//!
//! The C sources are the ones vendored in the `sundials-sys` 0.6.2 crate,
//! trimmed to what is built; `build.rs` compiles them with the `cc` crate.
//! Nothing else is needed at build time: the configuration header is
//! written by hand once (`sundials/include/sundials/sundials_config.h`,
//! the same on every platform) and the bindings below are committed,
//! generated by `tools/bindgen` (which needs libclang; run it only when the
//! vendored SUNDIALS changes). They hold on every 64-bit target: no layout
//! assertions, C `long` kept as `c_long`, fixed-width integers spelled as
//! Rust's, `FILE` opaque.


#[rustfmt::skip]
mod bindings;
pub use bindings::*;

#[cfg(test)]
mod tests {
    use super::*;
    use std::ptr;

    /// The library links and runs: a context, a vector, a dense LU solve.
    #[test]
    fn dense_lu_solves_a_system() {
        // SAFETY: plain SUNDIALS calls on objects created and freed here.
        unsafe {
            let mut ctx: SUNContext = ptr::null_mut();
            assert_eq!(SUNContext_Create(SUN_COMM_NULL, &mut ctx), 0);
            let n = 3;
            let b = N_VNew_Serial(n, ctx);
            let x = N_VNew_Serial(n, ctx);
            let a = SUNDenseMatrix(n, n, ctx);
            // A = [[4,1,0],[1,3,1],[0,1,2]], b = A * [1,2,3] = [6,10,8]
            let vals = [[4.0, 1.0, 0.0], [1.0, 3.0, 1.0], [0.0, 1.0, 2.0]];
            for j in 0..3 {
                let col = SUNDenseMatrix_Column(a, j as sunindextype);
                for (i, row) in vals.iter().enumerate() {
                    *col.add(i) = row[j];
                }
            }
            let bp = N_VGetArrayPointer(b);
            for (i, v) in [6.0, 10.0, 8.0].iter().enumerate() {
                *bp.add(i) = *v;
            }
            let ls = SUNLinSol_Dense(x, a, ctx);
            assert_eq!(SUNLinSolInitialize(ls), 0);
            assert_eq!(SUNLinSolSetup(ls, a), 0);
            assert_eq!(SUNLinSolSolve(ls, a, x, b, 0.0), 0);
            let xp = N_VGetArrayPointer(x);
            for (i, want) in [1.0, 2.0, 3.0].iter().enumerate() {
                assert!((*xp.add(i) - want).abs() < 1e-14);
            }
            SUNLinSolFree(ls);
            SUNMatDestroy(a);
            N_VDestroy(b);
            N_VDestroy(x);
            SUNContext_Free(&mut ctx);
        }
    }

    #[test]
    fn the_version_is_the_vendored_one() {
        let mut buf = [0 as std::os::raw::c_char; 32];
        // SAFETY: the buffer is long enough for the version string.
        unsafe { SUNDIALSGetVersion(buf.as_mut_ptr(), buf.len() as i32) };
        // SAFETY: SUNDIALS wrote a NUL-terminated string.
        let v = unsafe { std::ffi::CStr::from_ptr(buf.as_ptr()) };
        assert_eq!(v.to_str().unwrap(), "7.1.1");
    }
}
