//! Regenerates `lsim-sundials-sys/src/bindings.rs` from the vendored
//! SUNDIALS headers. Needs libclang; the engine's own build does not (the
//! output is committed). Run it after upgrading the vendored sources:
//!
//! ```sh
//! cargo run --manifest-path engine/crates/lsim-sundials-sys/tools/bindgen/Cargo.toml
//! ```
//!
//! The bindings must hold on every 64-bit target (Linux, macOS, Windows),
//! so nothing platform-specific may leak into them: no layout tests (they
//! assert this machine's sizes), C `long` stays `c_long` (32-bit on
//! Windows), fixed-width integers are spelled as Rust's (`int64_t` would
//! otherwise come out as glibc's `long`), `FILE` is opaque, and `#define`
//! constants are signed `i32`/`f64` like the `int` arguments they feed.
//! `extern` blocks are written `unsafe extern` (Rust 2024).

use std::path::PathBuf;

fn main() {
    let krate = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..").canonicalize().unwrap();
    let include = krate.join("sundials/include");
    let out = krate.join("src/bindings.rs");
    let fixed = ["int8_t", "int16_t", "int32_t", "int64_t", "uint8_t", "uint16_t", "uint32_t", "uint64_t"];
    let mut b = bindgen::Builder::default()
        .header(krate.join("wrapper.h").to_str().unwrap())
        .clang_arg(format!("-I{}", include.display()))
        .allowlist_function("(CV|IDA|KIN|SUN|N_V|SM_|SUNDIALS|SUNLinSol|SUNMat|SUNNonlinSol|SUNContext).*")
        .allowlist_type("(CV|IDA|KIN|SUN|N_V|sun|_generic_|SUNDIALS).*")
        .allowlist_var("(CV|IDA|KIN|SUN|SUNLS|SUNMAT|SUNDIALS|SUNNLS|SUN_|CSC_MAT|CSR_MAT).*")
        .blocklist_function(".*Print.*|.*Write.*|SUNLogger.*|SUNProfiler.*|SUNDIALSFileOpen|SUNDIALSFileClose|SUNContext_(Get|Set)(Logger|Profiler)")
        .blocklist_type("FILE|_IO_FILE|__sFILE|_iobuf|va_list|__va_list.*|__builtin_va_list|__gnuc_va_list|SUNLogger.*|SUNProfiler.*|_SUNLogger|_SUNProfiler|_IO_.*|__off.*_t")
        .default_macro_constant_type(bindgen::MacroTypeVariation::Signed)
        .default_enum_style(bindgen::EnumVariation::Consts)
        .layout_tests(false)
        .derive_default(false)
        .derive_debug(false)
        .generate_comments(false)
        .size_t_is_usize(true)
        .raw_line("// Generated by tools/bindgen from the vendored SUNDIALS 7.1.1 headers; do not edit.")
        .raw_line("#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals, dead_code, missing_docs)]")
        .raw_line("#![allow(clippy::all)]")
        .raw_line("/// C's `FILE`, opaque (only pointers to it cross the boundary).")
        .raw_line("pub enum FILE {}")
        .raw_line("/// SUNDIALS' logger, opaque.")
        .raw_line("pub type SUNLogger = *mut core::ffi::c_void;")
        .raw_line("/// SUNDIALS' profiler, opaque.")
        .raw_line("pub type SUNProfiler = *mut core::ffi::c_void;");
    for t in fixed {
        b = b.blocklist_type(t).blocklist_type(format!("__{t}"));
        let rust = match t {
            "int8_t" => "i8",
            "int16_t" => "i16",
            "int32_t" => "i32",
            "int64_t" => "i64",
            "uint8_t" => "u8",
            "uint16_t" => "u16",
            "uint32_t" => "u32",
            _ => "u64",
        };
        b = b.raw_line(format!("pub type {t} = {rust};"));
    }
    let text = b.generate().expect("bindgen").to_string();
    // Rust 2024 wants `unsafe extern` blocks; bindgen 0.68 predates it
    let text = text.replace("\nextern \"C\" {", "\nunsafe extern \"C\" {");
    std::fs::write(&out, text).expect("write");
    println!("wrote {}", out.display());
}
